#!/usr/bin/env bash
# Configures a new Ubuntu machine with nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP" # allow incoming connections from nginx
# sudo ufw status verbose: should return inactive
cd /var/www/ || return
sudo chmod 777 html
echo "Hello World!" > html/index.html
sudo chmod 755 html
cd ~ || return
sudo service nginx restart