#!/usr/bin/env bash
# Configures a new Ubuntu machine with nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
cd /var/www/
sudo chmod 777 html
echo 'Hello World!' > html/index.html
sudo chmod 755 html
cd ~
sudo service nginx restart