#!/usr/bin/env bash
# Configures a new Ubuntu machine with nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP" # allow incoming connections from nginx
# sudo ufw status verbose: should return inactive
cd /var/www/ || return
sudo chmod 777 html
echo "Hello World!" > html/index.html
sudo chmod 755 html
# Configure your Nginx server to redirect to another page
REDIRECT_CONFIG="\tlocation /redirect_me {\n\t\treturn 301 https://www.alxafrica.com;\n\t}"
sudo sed -i "52 a \    $REDIRECT_CONFIG" /etc/nginx/sites-enabled/default
# Configure your Nginx server to have a custom 404 page
cd /etc/nginx/
sudo mkdir -p html
sudo chmod 777 html
echo "Ceci n'est pas une page" > html/404.html
sudo chmod 755 html
CUSTOM404PAGE_CONFIG="\terror_page 404 /404.html;\n\tlocation /404 {\n\t\troot /etc/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "55 a \    $CUSTOM404PAGE_CONFIG" /etc/nginx/sites-enabled/default
# Configure your Nginx server with a custom header
CUSTOMHEADER_CONFIG="add_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "62 a \        $CUSTOMHEADER_CONFIG" /etc/nginx/nginx.conf
sudo service nginx restart