#!/usr/bin/env bash
# This is a script that displays to infinity and beyond indefinitely, and 'I am invincible!!!' when receiving a SIGTERM

for (( i=1; i>0; i++ ))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
