#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for the 9th iteration, displays Best School and then Hi

COUNT=0
while [ $COUNT -lt 11 ]
do
	if [ $COUNT -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	COUNT=$(( COUNT + 1 ))
done
