#!/usr/bin/env bash
# This script is displaying different text in a loop based on conditions

COUNT=1
while [ $COUNT -lt 11 ]
do
	if [ $COUNT -eq 4 ]
	then
		echo "bad luck"
	elif [ $COUNT -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	COUNT=$(( COUNT + 1 ))
done
